### PR TITLE
Enable new ompl planner to be used with amino

### PR DESCRIPTION
**Pull request by KeliangH**
Enable new ompl planner to be used with amino by adding hooks for changing the planner as well as retrieving the spaceinformation pointer

### CODE REVIEW

**Comment by ndantam** [comment]
Looks like the new header didn't get included in the distribution tarball build.  Please add it to noinst_HEADERS in Makefile.am.

**Comment by ndantam** [comment]
I think you still missed the internal header.  You can test on your local machine with `make distcheck` and `./scripts/docker-build.sh ubuntu-xenial && ./scripts/docker-check.sh ubuntu-xenial`.

**Comment by ndantam** [comment]
Do you need to access the specific implementation of `amino::sgSpaceInformation`?  If not, I think `aa_rx_mp_get_space_information()` should return a pointer to ompl::base::SpaceInformation rather than the amino-specific type.  This will let us change the implementation without breaking compatibility in the future.

**Comment by ndantam** [comment]
The internal header should not be included in the public header...

**Comment by ndantam** [comment]
Please check if 74162df resolves your issue

**Comment by KeliangH** [comment]
Yes it did. Thanks.

**Pull request closed without merging**
