### PR TITLE
Refactor collision set generation from scenegraph

### PR DESCRIPTION
**Pull request by KeliangH**

### CODE REVIEW

**Comment by ndantam** [comment]
- Flip argument order of `aa_rx_sg_cl_set_copy()` for consistency
- Pass in `cl_set` to `aa_rx_sg_get_collision()` rather than
  allocating within the function.  This is more flexible for the
  caller and puts allocation and deallocation together.  Then, the
  return code can indicate whether any collision has occured.
- Use separate functions to create planners rather than an enum.  This
  is more extensible since one can just add a new function rather
  than having to modify `aa_rx_mp_plan()`
- `aa_rx_sg_allow_collision()`: probably better to make two versions
  of this function, one that takes the (string) frame name and one
  that takes the (int) frame id.

**Comment by KeliangH** [comment]
For point number 2 regarding passing in cl_set, should the function check validity of the cl_set and clear the original cl_set?

**Comment by ndantam** [comment]
If we do not clear the original cl_set but only mark new collisions, 
then we can remove some of the merge operations on allowed configurations.

The caller can always explicitly clear the cl_set.  Probably more 
flexible to only mark the new collisions.

**Comment by ndantam** [comment]
Older FCL is still using boost::shared_ptr, so the change to std::shared_ptr breaks.  This should probably be a configure test to determine which FCL is being used.

**Comment by ndantam** [comment]
Please see if the added configure test for shared_ptr types in commit 659396d builds against your FCL.

**Comment by ndantam** [comment]
ad18b54 refactors planner creation, fixes a leak, and renames some symbols for consistency.

**Comment by ndantam** [comment]
8cff324 modifies the API to reduce necessary object management and allow planner parameter configuration.

**Pull request merged**
