### PR TITLE
Fix behavior in aa_rx_sg_copy

### PR DESCRIPTION
**Pull request by KeliangH**
Fix the behavior where allowed configs are not copied in aa_rx_sg_copy. Allowed configs stored in the scenegraph (not the motion planning instance) represent valid configurations of the scene, and therefore should be copied when copying the scenegraph.

### CODE REVIEW

**Comment by ndantam** [comment]
You probably need to do a deep copy rather than shallow pointer assignment.  Otherwise, when you delete one of the scenegraphs, it will destroy the allowed collision set for both itself and the copy/original.

**Comment by KeliangH** [comment]
The allowed field in scenegraph is of type std::set<std::pair<const char*, const char*> >, so calling operator= should copy each element of the original set into the new one, calling std::pair's copy constructor. So this should be OK?

**Comment by ndantam** [comment]
Ok, the set's actual data is a pair of C strings (char*), which are (or should be) the frame names stored as C++ strings in the vector of amino::SceneFrame::name.  The operator= will result in the copied scenegraph's set holding pointers to the original scenegraph's names, which will break if the original scenegraph is deleted.

Related: aa_rx_sg_allow_collision_name() should probably pull frame name pointers from the std::string in amino::SceneFrame::name rather than just copying its arguments (which could be temporary values).

**Comment by KeliangH** [comment]
I realized that this never made it into the main repo. Was there a reason for that? I merged in the new changes from the master branch, because I need them for my work. Let me know how you would like for this change to be included in the main amino repo.

**Comment by ndantam** [comment]
9ea63ae

**Pull request closed without merging**
